#!/bin/bash

echo "Incepem compilarea ..."
gcc scanner.c radiotap-parser.c dbaccess.c -o wrlsScan -lpcap -lcrypto -lssl -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -ldl -I/usr/include/mysql -DBIG_JOINS=1 -fno-strict-aliasing -g
echo "... Done"
